### ISSUE TITLE
Upgrade to latest Python

### ISSUE THREAD

**Issue by Stewart86** [Stewart86/roadtaxTracker#13]
Current Python version is outdated. To upgrade to latest Python and all other packages.

**Comment by imanvanassum** [comment]
I'll pick this up, looks like a fun application.

**Comment by imanvanassum** [comment]
https://github.com/Stewart86/roadtaxTracker/pull/15

That's not all obviously, but a start (I didn't realise the rest of the app doesn't have unittests...)

**Comment by Stewart86** [comment]
Sorry I have to revert the pull request as I reaslise this project is using a piplock file, which is using the pipenv package for installation. please re submit a PR with pipenv installation.

**Comment by imanvanassum** [comment]
Cool but then why close the issue?

**Comment by Stewart86** [comment]
I have addressed the issue with my latest push and updated it to python 3.8 with pipenv.
