### ISSUE TITLE
Multi vehicle selection

### ISSUE THREAD

**Issue by Stewart86** [Stewart86/roadtaxTracker#18]
Currently selection of vehicle can only be done to a single vehicle.
Multiple selection will be helpful when one needs to make similar changes to multiple vehicles at once.

**Comment by Sudipt-panda** [comment]
Can I start working on this?
Also, this would be my 1st contribution, so if you can give me a direction to start working on this issue, it will be really helpful.

Thanks in advance.

**Comment by Stewart86** [comment]
@Sudipt-panda sure go ahead!

**Comment by Stewart86** [comment]
To start working on it. first you need to get the setup done. follow the instructions on the readme on the main page. 
from there just to have a go and see how the app works and read up on the code.
Might be a little overwhelming for a start. But I am pretty sure this project is better than a lot of other up-for-grab out there. 
once you understand the logic then you can try solve the problem here. or you could try on any other issues raised in the project. You can even add on to the issue list if you find any.
