### ISSUE TITLE
The Function `csv_writer()` does not generate new file if not exist

### ISSUE THREAD

**Issue by Stewart86** [Stewart86/roadtaxTracker#19]
`csv_writer` should create a new file if it doesn't exist.

**Comment by imanvanassum** [comment]
This is a really easy fix ( w -> w+ as the param for open ) but after going through the code, this function seems to never get called anywhere? It's defined in vehicleGen, but never invoked.

Depending on what the function is supposed to do append may be better than write, to prevent overwriting contents.

**Comment by Stewart86** [comment]
Yup, I reckon so, but just maybe let someone else try fixing it as a coding practice.

this function only get called by using the terminal. It is to generate a list of dummy vehicles for people to play with (instead of a empty database). For now, appending or writing doesn't matter much unless someone want to mix a list of dummy vehicles with their own?

**Comment by sakshatshinde** [comment]
Fixed this issue, and created a pull request : [Here](https://github.com/Stewart86/roadtaxTracker/pull/24)

**Comment by Stewart86** [comment]
@sakshatshinde Thank for the pull request.
